using System.Collections.Generic;
using UnityEngine;

public class Date : MonoBehaviour
{
    // ===== Date Data =====
    public static Dictionary<string, Event> eventDates = new Dictionary<string, Event>()
    {
        // 나이/월/일
        { "0/1/2",      new Event("출생신고 외출", "")},
        { "0/2/16",     new Event("쇼핑몰 외출", "")},
        { "0/6/26",     new Event("초능력 대화", "")},

        { "3/2/29",     new Event("정다빈 첫등장", "")},
        { "3/3/27",     new Event("정다빈 생일", "")},
        { "3/5/12",     new Event("논문 자장가", "")},

        { "5/1/20",     new Event("정다빈 가족과 우연히 극장에서 마주침", "Theater")},
        { "5/2/17",     new Event("채현 첫등장", "")},
        { "5/2/27",     new Event("채현에게 마술 공연 발각!", "Magic")},
        { "5/3/5",      new Event("한국어 교육 시도", "")},
        { "5/3/27",     new Event("정다빈 생일", "")},
        { "5/4/26",     new Event("세가족 소풍", "")},
        { "5/5/8",      new Event("어버이날", "")},

        { "8/1/18",     new Event("채현 생일", "")},
        { "8/1/24",     new Event("초등학교 입학 준비", "")},
        { "8/2/2",      new Event("입학식, 시아시우 첫 등장", "")},
        { "8/3/19",    new Event("현장체험학습", "")},
        { "8/3/27",    new Event("정다빈 생일", "")},
        { "8/4/5",    new Event("학원에서 정다빈과 마주침", "Subject")},
        { "8/5/3",     new Event("시아시우 생일", "")},
        { "8/5/10",    new Event("반친구와 싸움", "")},
        { "8/6/12",    new Event("무술 학원에서 시아 만남", "Exercise")},
        { "8/6/13",    new Event("무술 학원에서 시우 만남", "Exercise")},

        { "12/1/1",     new Event("생일파티", "")},
        { "12/1/14",    new Event("학원 앞에서 시우 만남", "Language")},
        { "12/1/18",    new Event("채현 생일", "")},
        { "12/1/32",    new Event("트럼본 배운김에 채현에게 시범", "Trombone")},
        { "12/2/15",     new Event("시아 가출해서 우리집 찾아옴", "Cook")},
        { "12/2/25",    new Event("첫 핸드폰", "")},
        { "12/4/11",    new Event("체육대회", "")},
        { "12/4/25",     new Event("시아 아가씨의 프라이빗 극장", "Theater")},
        { "12/5/3",    new Event("시아시우 생일 (시아)", "")},
        { "12/5/13",     new Event("집에 가다가 외국인에게 붙잡힌 시우 구출", "Language")},
        { "12/6/21",    new Event("인씨 가문 대저택 방문", "")},
        { "12/6/34",    new Event("이민 가는 채현을 위한 단독 공연", "Magic")},

        { "15/1/12",    new Event("채현 이민 배웅", "")},
        { "15/1/25",    new Event("시우 도련님과 방과후 다도 모임", "TeaCeremony")},
        { "15/2/11",     new Event("학원에서 다빈쓰 마주침", "Language")},
        { "15/2/29",    new Event("무술 메이트 시아 아가씨", "Exercise")},
        { "15/3/15",     new Event("힘들어보이는 다빈쓰를 위한 차한잔", "TeaCeremony")},
        { "15/3/27",    new Event("정다빈 생일", "")},
        { "15/4/7",     new Event("학원 땡땡이 치려는 다빈쓰 목격!", "Subject")},
        { "15/4/25",    new Event("승진 기념 파티", "")},
        { "15/5/3",     new Event("시아시우 생일", "")},
        { "15/5/28",    new Event("시아 아가씨의 모델이 되어보자", "Art")},
        { "15/6/11",    new Event("시우 도련님과 방과후 독서 모임", "ReadBook")},
        { "15/6/31",    new Event("크리스마스 선물 증정식", "")},

        { "16/1/15",    new Event("카페알바 슈슈 관람하는 부잣집 도련님", "Cafe")},
        { "16/1/26",    new Event("단둘이 여행", "")},
        { "16/4/18",    new Event("추석", "")},
        { "16/4/28",    new Event("옷가게 알바 슈슈 구경하는 부잣집 아가씨 시아", "Clothes")},
        { "16/5/3",    new Event("시아시우 생일", "")},
        { "16/6/19",    new Event("중학교 졸업식", "")},
        
        { "17/1/7",    new Event("다빈쓰랑 같이 컴퓨터 활용 뭐시기 자격증 시험봄", "Computer")},
        { "17/1/18",    new Event("채현 생일", "")},
        { "17/1/30",    new Event("채현 컴백 기념 외출", "Theater")},
        { "17/2/3",    new Event("알바 진상 상대", "")},
        { "17/2/15",    new Event("알바 중 다빈쓰 마주침", "Cafe")},
        { "17/2/31",    new Event("물류센터 다녀와서 채현 만남", "LogisticsCenter")},
        { "17/3/8",    new Event("채현이랑 같이 극장 다녀옴", "Theater")},
        { "17/3/22",    new Event("시아 아가씨와 방과후 미적 감각을 늘리기 위한 활동", "Art")},
        { "17/3/27",    new Event("정다빈 생일", "")},
        { "17/3/33",    new Event("초능력 수행평가", "")},
        { "17/4/11",    new Event("채현과 등산 겸 폭포 수련", "Waterfall")},
        { "17/4/20",    new Event("갑작스런 리퀘스트! 다빈쓰 동생 돌보기", "Babysitter")},
        { "17/5/3",    new Event("시아시우 생일", "")},
        { "17/5/10",    new Event("수학여행 준비", "")},
        { "17/5/19",    new Event("수학여행", "")},
        { "17/6/7",    new Event("오랜만에 시우 도련님과 독서 모임", "ReadBook")},
        { "17/6/28",    new Event("백수 방문객 채현을 위한 음식 대접", "Cook")},
        
        { "18/1/11",    new Event("채현에게 트럼본 실력 검사받기", "Trombone")},
        { "18/1/18",    new Event("채현 생일", "")},
        { "18/1/25",    new Event("오랜만에 도장 방문한 시우 도련님과 대련", "Exercise")},
        { "18/2/9",    new Event("폭표 명상하는 슈슈를 보며 명상하는 다빈쓰", "Waterfall")},
        { "18/2/26",    new Event("시험기간 도서관", "")},
        { "18/3/3",    new Event("시험 당일", "")},
        { "18/3/13",    new Event("놀이공원 방문", "")},
        { "18/3/27",    new Event("정다빈 생일", "")},
        { "18/4/6",    new Event("시우 도련님과 도서관 방문", "ReadBook")},
        { "18/4/26",    new Event("채현의 요리교실", "Cook")},
        { "18/5/3",    new Event("시아시우 생일 (시우)", "")},
        { "18/5/24",    new Event("시아 아가씨랑 (비싼)연극 보는 날", "Theater")},
        { "18/6/14",    new Event("시아 아가씨와 외출, 외국인 만남  어버버", "Language")},
        { "18/6/26",    new Event("친구들과 게임", "")},
        { "18/6/31",    new Event("다빈쓰에게 수능 공부 도움받기", "Su-neung")},
        
        { "19/1/4",    new Event("다빈쓰랑 도서관 데이트ㅠㅠ", "Su-neung")},
        { "19/1/18",    new Event("채현 생일", "")},
        { "19/1/31",    new Event("채현자식 과외 시켜주기", "Su-neung")},
        { "19/2/17",    new Event("심신 안정을 위한 시우 도련님과 다도 모임", "TeaCeremony")},
        { "19/3/17",    new Event("시아 아가씨에게 배우는 리얼 사회생활", "SocialLife")},
        { "19/3/27",    new Event("정다빈 생일", "")},
        { "19/4/4",    new Event("플레이어 생일파티", "")},
        { "19/5/3",    new Event("시아시우 생일", "")},
        { "19/5/17",    new Event("수능", "")},
        { "19/6/10",    new Event("학교 축제 준비", "")},
        { "19/6/12",    new Event("학교 축제", "")},
        { "19/6/25",    new Event("졸업 전 기념 여행", "")},
        { "19/6/35",    new Event("고등학교 졸업식", "")}
    };
}
